## Countries

In [1]:
import pygadm
import pandas as pd
import geopandas as gpd
from tqdm import tqdm
from pathlib import Path
import pycountry
import os

## Rasters

In [2]:
checkpoint_path = "../results/country_confustion_matrix.parquet"
removed = ["AUS", "BRA", "CAN", "USA", "RUS", "GRL", "MEX", "CHL", "IDN"]

if os.path.exists(checkpoint_path):
    df = pd.read_parquet(checkpoint_path)
    completed = set(df.gid.to_list())
else:
    df = pd.DataFrame(columns=["country", "gid", "pixel_count", "TN", "FP", "FN", "TP"])
    completed = set()

completed.update(removed)

In [3]:
df

           country  gid  pixel_count       TN     FP      FN     TP
0      Philippines  PHL      1416080  1224155  10158  135658  46109
1         Pitcairn  PCN          278      278    278     278    278
2           Panama  PAN       356926   336815   5401    5747   8963
3             Oman  OMN      1543598  1470891  43239    6194  23274
4            Nepal  NPL       782268   629907   3010  140731   8620
..             ...  ...          ...      ...    ...     ...    ...
145  Åland Islands  ALA        13830    13470     25     219    116
146         Angola  AGO      5977578  5899914  14557   49634  13473
147    Afghanistan  AFG      3614259  3539717  18928   46755   8859
148          Aruba  ABW            0        0      0       0      0
149          Aruba  ABW          870      262     47      21    540

[150 rows x 7 columns]

In [31]:
list(pycountry.countries)

[Country(alpha_2='AW', alpha_3='ABW', flag='🇦🇼', name='Aruba', numeric='533'),
 Country(alpha_2='AF', alpha_3='AFG', flag='🇦🇫', name='Afghanistan', numeric='004', official_name='Islamic Republic of Afghanistan'),
 Country(alpha_2='AO', alpha_3='AGO', flag='🇦🇴', name='Angola', numeric='024', official_name='Republic of Angola'),
 Country(alpha_2='AI', alpha_3='AIA', flag='🇦🇮', name='Anguilla', numeric='660'),
 Country(alpha_2='AX', alpha_3='ALA', flag='🇦🇽', name='Åland Islands', numeric='248'),
 Country(alpha_2='AL', alpha_3='ALB', flag='🇦🇱', name='Albania', numeric='008', official_name='Republic of Albania'),
 Country(alpha_2='AD', alpha_3='AND', flag='🇦🇩', name='Andorra', numeric='020', official_name='Principality of Andorra'),
 Country(alpha_2='AE', alpha_3='ARE', flag='🇦🇪', name='United Arab Emirates', numeric='784'),
 Country(alpha_2='AR', alpha_3='ARG', flag='🇦🇷', name='Argentina', numeric='032', official_name='Argentine Republic'),
 Country(alpha_2='AM', alpha_3='ARM', flag='🇦🇲', name='Armenia', numeric='051', official_name='Republic of Armenia'),
 Country(alpha_2='AS', alpha_3='ASM', flag='🇦🇸', name='American Samoa', numeric='016'),
 Country(alpha_2='AQ', alpha_3='ATA', flag='🇦🇶', name='Antarctica', numeric='010'),
 Country(alpha_2='TF', alpha_3='ATF', flag='🇹🇫', name='French Southern Territories', numeric='260'),
 Country(alpha_2='AG', alpha_3='ATG', flag='🇦🇬', name='Antigua and Barbuda', numeric='028'),
 Country(alpha_2='AU', alpha_3='AUS', flag='🇦🇺', name='Australia', numeric='036'),
 Country(alpha_2='AT', alpha_3='AUT', flag='🇦🇹', name='Austria', numeric='040', official_name='Republic of Austria'),
 Country(alpha_2='AZ', alpha_3='AZE', flag='🇦🇿', name='Azerbaijan', numeric='031', official_name='Republic of Azerbaijan'),
 Country(alpha_2='BI', alpha_3='BDI', flag='🇧🇮', name='Burundi', numeric='108', official_name='Republic of Burundi'),
 Country(alpha_2='BE', alpha_3='BEL', flag='🇧🇪', name='Belgium', numeric='056', official_name='Kingdom of Belgium'),
 Country(alpha_2='BJ', alpha_3='BEN', flag='🇧🇯', name='Benin', numeric='204', official_name='Republic of Benin'),
 Country(alpha_2='BQ', alpha_3='BES', flag='🇧🇶', name='Bonaire, Sint Eustatius and Saba', numeric='535', official_name='Bonaire, Sint Eustatius and Saba'),
 Country(alpha_2='BF', alpha_3='BFA', flag='🇧🇫', name='Burkina Faso', numeric='854'),
 Country(alpha_2='BD', alpha_3='BGD', flag='🇧🇩', name='Bangladesh', numeric='050', official_name="People's Republic of Bangladesh"),
 Country(alpha_2='BG', alpha_3='BGR', flag='🇧🇬', name='Bulgaria', numeric='100', official_name='Republic of Bulgaria'),
 Country(alpha_2='BH', alpha_3='BHR', flag='🇧🇭', name='Bahrain', numeric='048', official_name='Kingdom of Bahrain'),
 Country(alpha_2='BS', alpha_3='BHS', flag='🇧🇸', name='Bahamas', numeric='044', official_name='Commonwealth of the Bahamas'),
 Country(alpha_2='BA', alpha_3='BIH', flag='🇧🇦', name='Bosnia and Herzegovina', numeric='070', official_name='Republic of Bosnia and Herzegovina'),
 Country(alpha_2='BL', alpha_3='BLM', flag='🇧🇱', name='Saint Barthélemy', numeric='652'),
 Country(alpha_2='BY', alpha_3='BLR', flag='🇧🇾', name='Belarus', numeric='112', official_name='Republic of Belarus'),
 Country(alpha_2='BZ', alpha_3='BLZ', flag='🇧🇿', name='Belize', numeric='084'),
 Country(alpha_2='BM', alpha_3='BMU', flag='🇧🇲', name='Bermuda', numeric='060'),
 Country(alpha_2='BO', alpha_3='BOL', common_name='Bolivia', flag='🇧🇴', name='Bolivia, Plurinational State of', numeric='068', official_name='Plurinational State of Bolivia'),
 Country(alpha_2='BR', alpha_3='BRA', flag='🇧🇷', name='Brazil', numeric='076', official_name='Federative Republic of Brazil'),
 Country(alpha_2='BB', alpha_3='BRB', flag='🇧🇧', name='Barbados', numeric='052'),
 Country(alpha_2='BN', alpha_3='BRN', flag='🇧🇳', name='Brunei Darussalam', numeric='096'),
 Country(alpha_2='BT', alpha_3='BTN', flag='🇧🇹', name='Bhutan', numeric='064', official_name='Kingdom of Bhutan'),
 Country(alpha_2='BV', alpha_3='BVT', flag='🇧🇻', name='Bouvet Island', numeric='074'),
 Country(alpha_2='BW', alpha_3='BWA', flag='🇧🇼', name='Botswana', numeric='072', official_name='Republic of Botswana'),
 Country(alpha_2='CF', alpha_3='CAF', flag='🇨🇫', name='Central African Republic', numeric='140'),
 Country(alpha_2='CA', alpha_3='CAN', flag='🇨🇦', name='Canada', numeric='124'),
 Country(alpha_2='CC', alpha_3='CCK', flag='🇨🇨', name='Cocos (Keeling) Islands', numeric='166'),
 Country(alpha_2='CH', alpha_3='CHE', flag='🇨🇭', name='Switzerland', numeric='756', official_name='Swiss Confederation'),
 Country(alpha_2='CL', alpha_3='CHL', flag='🇨🇱', name='Chile', numeric='152', official_name='Republic of Chile'),
 Country(alpha_2='CN', alpha_3='CHN', flag='🇨🇳', name='China', numeric='156', official_name="People's Republic of China"),
 Country(alpha_2='CI', alpha_3='CIV', flag='🇨🇮', name="Côte d'Ivoire", numeric='384', official_name="Republic of Côte d'Ivoire"),
 Country(alpha_2='CM', alpha_3='CMR', flag='🇨🇲', name='Cameroon', numeric='120', official_name='Republic of Cameroon'),
 Country(alpha_2='CD', alpha_3='COD', flag='🇨🇩', name='Congo, The Democratic Republic of the', numeric='180'),
 Country(alpha_2='CG', alpha_3='COG', flag='🇨🇬', name='Congo', numeric='178', official_name='Republic of the Congo'),
 Country(alpha_2='CK', alpha_3='COK', flag='🇨🇰', name='Cook Islands', numeric='184'),
 Country(alpha_2='CO', alpha_3='COL', flag='🇨🇴', name='Colombia', numeric='170', official_name='Republic of Colombia'),
 Country(alpha_2='KM', alpha_3='COM', flag='🇰🇲', name='Comoros', numeric='174', official_name='Union of the Comoros'),
 Country(alpha_2='CV', alpha_3='CPV', flag='🇨🇻', name='Cabo Verde', numeric='132', official_name='Republic of Cabo Verde'),
 Country(alpha_2='CR', alpha_3='CRI', flag='🇨🇷', name='Costa Rica', numeric='188', official_name='Republic of Costa Rica'),
 Country(alpha_2='CU', alpha_3='CUB', flag='🇨🇺', name='Cuba', numeric='192', official_name='Republic of Cuba'),
 Country(alpha_2='CW', alpha_3='CUW', flag='🇨🇼', name='Curaçao', numeric='531', official_name='Curaçao'),
 Country(alpha_2='CX', alpha_3='CXR', flag='🇨🇽', name='Christmas Island', numeric='162'),
 Country(alpha_2='KY', alpha_3='CYM', flag='🇰🇾', name='Cayman Islands', numeric='136'),
 Country(alpha_2='CY', alpha_3='CYP', flag='🇨🇾', name='Cyprus', numeric='196', official_name='Republic of Cyprus'),
 Country(alpha_2='CZ', alpha_3='CZE', flag='🇨🇿', name='Czechia', numeric='203', official_name='Czech Republic'),
 Country(alpha_2='DE', alpha_3='DEU', flag='🇩🇪', name='Germany', numeric='276', official_name='Federal Republic of Germany'),
 Country(alpha_2='DJ', alpha_3='DJI', flag='🇩🇯', name='Djibouti', numeric='262', official_name='Republic of Djibouti'),
 Country(alpha_2='DM', alpha_3='DMA', flag='🇩🇲', name='Dominica', numeric='212', official_name='Commonwealth of Dominica'),
 Country(alpha_2='DK', alpha_3='DNK', flag='🇩🇰', name='Denmark', numeric='208', official_name='Kingdom of Denmark'),
 Country(alpha_2='DO', alpha_3='DOM', flag='🇩🇴', name='Dominican Republic', numeric='214'),
 Country(alpha_2='DZ', alpha_3='DZA', flag='🇩🇿', name='Algeria', numeric='012', official_name="People's Democratic Republic of Algeria"),
 Country(alpha_2='EC', alpha_3='ECU', flag='🇪🇨', name='Ecuador', numeric='218', official_name='Republic of Ecuador'),
 Country(alpha_2='EG', alpha_3='EGY', flag='🇪🇬', name='Egypt', numeric='818', official_name='Arab Republic of Egypt'),
 Country(alpha_2='ER', alpha_3='ERI', flag='🇪🇷', name='Eritrea', numeric='232', official_name='the State of Eritrea'),
 Country(alpha_2='EH', alpha_3='ESH', flag='🇪🇭', name='Western Sahara', numeric='732'),
 Country(alpha_2='ES', alpha_3='ESP', flag='🇪🇸', name='Spain', numeric='724', official_name='Kingdom of Spain'),
 Country(alpha_2='EE', alpha_3='EST', flag='🇪🇪', name='Estonia', numeric='233', official_name='Republic of Estonia'),
 Country(alpha_2='ET', alpha_3='ETH', flag='🇪🇹', name='Ethiopia', numeric='231', official_name='Federal Democratic Republic of Ethiopia'),
 Country(alpha_2='FI', alpha_3='FIN', flag='🇫🇮', name='Finland', numeric='246', official_name='Republic of Finland'),
 Country(alpha_2='FJ', alpha_3='FJI', flag='🇫🇯', name='Fiji', numeric='242', official_name='Republic of Fiji'),
 Country(alpha_2='FK', alpha_3='FLK', flag='🇫🇰', name='Falkland Islands (Malvinas)', numeric='238'),
 Country(alpha_2='FR', alpha_3='FRA', flag='🇫🇷', name='France', numeric='250', official_name='French Republic'),
 Country(alpha_2='FO', alpha_3='FRO', flag='🇫🇴', name='Faroe Islands', numeric='234'),
 Country(alpha_2='FM', alpha_3='FSM', flag='🇫🇲', name='Micronesia, Federated States of', numeric='583', official_name='Federated States of Micronesia'),
 Country(alpha_2='GA', alpha_3='GAB', flag='🇬🇦', name='Gabon', numeric='266', official_name='Gabonese Republic'),
 Country(alpha_2='GB', alpha_3='GBR', flag='🇬🇧', name='United Kingdom', numeric='826', official_name='United Kingdom of Great Britain and Northern Ireland'),
 Country(alpha_2='GE', alpha_3='GEO', flag='🇬🇪', name='Georgia', numeric='268'),
 Country(alpha_2='GG', alpha_3='GGY', flag='🇬🇬', name='Guernsey', numeric='831'),
 Country(alpha_2='GH', alpha_3='GHA', flag='🇬🇭', name='Ghana', numeric='288', official_name='Republic of Ghana'),
 Country(alpha_2='GI', alpha_3='GIB', flag='🇬🇮', name='Gibraltar', numeric='292'),
 Country(alpha_2='GN', alpha_3='GIN', flag='🇬🇳', name='Guinea', numeric='324', official_name='Republic of Guinea'),
 Country(alpha_2='GP', alpha_3='GLP', flag='🇬🇵', name='Guadeloupe', numeric='312'),
 Country(alpha_2='GM', alpha_3='GMB', flag='🇬🇲', name='Gambia', numeric='270', official_name='Republic of the Gambia'),
 Country(alpha_2='GW', alpha_3='GNB', flag='🇬🇼', name='Guinea-Bissau', numeric='624', official_name='Republic of Guinea-Bissau'),
 Country(alpha_2='GQ', alpha_3='GNQ', flag='🇬🇶', name='Equatorial Guinea', numeric='226', official_name='Republic of Equatorial Guinea'),
 Country(alpha_2='GR', alpha_3='GRC', flag='🇬🇷', name='Greece', numeric='300', official_name='Hellenic Republic'),
 Country(alpha_2='GD', alpha_3='GRD', flag='🇬🇩', name='Grenada', numeric='308'),
 Country(alpha_2='GL', alpha_3='GRL', flag='🇬🇱', name='Greenland', numeric='304'),
 Country(alpha_2='GT', alpha_3='GTM', flag='🇬🇹', name='Guatemala', numeric='320', official_name='Republic of Guatemala'),
 Country(alpha_2='GF', alpha_3='GUF', flag='🇬🇫', name='French Guiana', numeric='254'),
 Country(alpha_2='GU', alpha_3='GUM', flag='🇬🇺', name='Guam', numeric='316'),
 Country(alpha_2='GY', alpha_3='GUY', flag='🇬🇾', name='Guyana', numeric='328', official_name='Republic of Guyana'),
 Country(alpha_2='HK', alpha_3='HKG', flag='🇭🇰', name='Hong Kong', numeric='344', official_name='Hong Kong Special Administrative Region of China'),
 Country(alpha_2='HM', alpha_3='HMD', flag='🇭🇲', name='Heard Island and McDonald Islands', numeric='334'),
 Country(alpha_2='HN', alpha_3='HND', flag='🇭🇳', name='Honduras', numeric='340', official_name='Republic of Honduras'),
 Country(alpha_2='HR', alpha_3='HRV', flag='🇭🇷', name='Croatia', numeric='191', official_name='Republic of Croatia'),
 Country(alpha_2='HT', alpha_3='HTI', flag='🇭🇹', name='Haiti', numeric='332', official_name='Republic of Haiti'),
 Country(alpha_2='HU', alpha_3='HUN', flag='🇭🇺', name='Hungary', numeric='348', official_name='Hungary'),
 Country(alpha_2='ID', alpha_3='IDN', flag='🇮🇩', name='Indonesia', numeric='360', official_name='Republic of Indonesia'),
 Country(alpha_2='IM', alpha_3='IMN', flag='🇮🇲', name='Isle of Man', numeric='833'),
 Country(alpha_2='IN', alpha_3='IND', flag='🇮🇳', name='India', numeric='356', official_name='Republic of India'),
 Country(alpha_2='IO', alpha_3='IOT', flag='🇮🇴', name='British Indian Ocean Territory', numeric='086'),
 Country(alpha_2='IE', alpha_3='IRL', flag='🇮🇪', name='Ireland', numeric='372'),
 Country(alpha_2='IR', alpha_3='IRN', common_name='Iran', flag='🇮🇷', name='Iran, Islamic Republic of', numeric='364', official_name='Islamic Republic of Iran'),
 Country(alpha_2='IQ', alpha_3='IRQ', flag='🇮🇶', name='Iraq', numeric='368', official_name='Republic of Iraq'),
 Country(alpha_2='IS', alpha_3='ISL', flag='🇮🇸', name='Iceland', numeric='352', official_name='Republic of Iceland'),
 Country(alpha_2='IL', alpha_3='ISR', flag='🇮🇱', name='Israel', numeric='376', official_name='State of Israel'),
 Country(alpha_2='IT', alpha_3='ITA', flag='🇮🇹', name='Italy', numeric='380', official_name='Italian Republic'),
 Country(alpha_2='JM', alpha_3='JAM', flag='🇯🇲', name='Jamaica', numeric='388'),
 Country(alpha_2='JE', alpha_3='JEY', flag='🇯🇪', name='Jersey', numeric='832'),
 Country(alpha_2='JO', alpha_3='JOR', flag='🇯🇴', name='Jordan', numeric='400', official_name='Hashemite Kingdom of Jordan'),
 Country(alpha_2='JP', alpha_3='JPN', flag='🇯🇵', name='Japan', numeric='392'),
 Country(alpha_2='KZ', alpha_3='KAZ', flag='🇰🇿', name='Kazakhstan', numeric='398', official_name='Republic of Kazakhstan'),
 Country(alpha_2='KE', alpha_3='KEN', flag='🇰🇪', name='Kenya', numeric='404', official_name='Republic of Kenya'),
 Country(alpha_2='KG', alpha_3='KGZ', flag='🇰🇬', name='Kyrgyzstan', numeric='417', official_name='Kyrgyz Republic'),
 Country(alpha_2='KH', alpha_3='KHM', flag='🇰🇭', name='Cambodia', numeric='116', official_name='Kingdom of Cambodia'),
 Country(alpha_2='KI', alpha_3='KIR', flag='🇰🇮', name='Kiribati', numeric='296', official_name='Republic of Kiribati'),
 Country(alpha_2='KN', alpha_3='KNA', flag='🇰🇳', name='Saint Kitts and Nevis', numeric='659'),
 Country(alpha_2='KR', alpha_3='KOR', common_name='South Korea', flag='🇰🇷', name='Korea, Republic of', numeric='410'),
 Country(alpha_2='KW', alpha_3='KWT', flag='🇰🇼', name='Kuwait', numeric='414', official_name='State of Kuwait'),
 Country(alpha_2='LA', alpha_3='LAO', common_name='Laos', flag='🇱🇦', name="Lao People's Democratic Republic", numeric='418'),
 Country(alpha_2='LB', alpha_3='LBN', flag='🇱🇧', name='Lebanon', numeric='422', official_name='Lebanese Republic'),
 Country(alpha_2='LR', alpha_3='LBR', flag='🇱🇷', name='Liberia', numeric='430', official_name='Republic of Liberia'),
 Country(alpha_2='LY', alpha_3='LBY', flag='🇱🇾', name='Libya', numeric='434', official_name='Libya'),
 Country(alpha_2='LC', alpha_3='LCA', flag='🇱🇨', name='Saint Lucia', numeric='662'),
 Country(alpha_2='LI', alpha_3='LIE', flag='🇱🇮', name='Liechtenstein', numeric='438', official_name='Principality of Liechtenstein'),
 Country(alpha_2='LK', alpha_3='LKA', flag='🇱🇰', name='Sri Lanka', numeric='144', official_name='Democratic Socialist Republic of Sri Lanka'),
 Country(alpha_2='LS', alpha_3='LSO', flag='🇱🇸', name='Lesotho', numeric='426', official_name='Kingdom of Lesotho'),
 Country(alpha_2='LT', alpha_3='LTU', flag='🇱🇹', name='Lithuania', numeric='440', official_name='Republic of Lithuania'),
 Country(alpha_2='LU', alpha_3='LUX', flag='🇱🇺', name='Luxembourg', numeric='442', official_name='Grand Duchy of Luxembourg'),
 Country(alpha_2='LV', alpha_3='LVA', flag='🇱🇻', name='Latvia', numeric='428', official_name='Republic of Latvia'),
 Country(alpha_2='MO', alpha_3='MAC', flag='🇲🇴', name='Macao', numeric='446', official_name='Macao Special Administrative Region of China'),
 Country(alpha_2='MF', alpha_3='MAF', flag='🇲🇫', name='Saint Martin (French part)', numeric='663'),
 Country(alpha_2='MA', alpha_3='MAR', flag='🇲🇦', name='Morocco', numeric='504', official_name='Kingdom of Morocco'),
 Country(alpha_2='MC', alpha_3='MCO', flag='🇲🇨', name='Monaco', numeric='492', official_name='Principality of Monaco'),
 Country(alpha_2='MD', alpha_3='MDA', common_name='Moldova', flag='🇲🇩', name='Moldova, Republic of', numeric='498', official_name='Republic of Moldova'),
 Country(alpha_2='MG', alpha_3='MDG', flag='🇲🇬', name='Madagascar', numeric='450', official_name='Republic of Madagascar'),
 Country(alpha_2='MV', alpha_3='MDV', flag='🇲🇻', name='Maldives', numeric='462', official_name='Republic of Maldives'),
 Country(alpha_2='MX', alpha_3='MEX', flag='🇲🇽', name='Mexico', numeric='484', official_name='United Mexican States'),
 Country(alpha_2='MH', alpha_3='MHL', flag='🇲🇭', name='Marshall Islands', numeric='584', official_name='Republic of the Marshall Islands'),
 Country(alpha_2='MK', alpha_3='MKD', flag='🇲🇰', name='North Macedonia', numeric='807', official_name='Republic of North Macedonia'),
 Country(alpha_2='ML', alpha_3='MLI', flag='🇲🇱', name='Mali', numeric='466', official_name='Republic of Mali'),
 Country(alpha_2='MT', alpha_3='MLT', flag='🇲🇹', name='Malta', numeric='470', official_name='Republic of Malta'),
 Country(alpha_2='MM', alpha_3='MMR', flag='🇲🇲', name='Myanmar', numeric='104', official_name='Republic of Myanmar'),
 Country(alpha_2='ME', alpha_3='MNE', flag='🇲🇪', name='Montenegro', numeric='499', official_name='Montenegro'),
 Country(alpha_2='MN', alpha_3='MNG', flag='🇲🇳', name='Mongolia', numeric='496'),
 Country(alpha_2='MP', alpha_3='MNP', flag='🇲🇵', name='Northern Mariana Islands', numeric='580', official_name='Commonwealth of the Northern Mariana Islands'),
 Country(alpha_2='MZ', alpha_3='MOZ', flag='🇲🇿', name='Mozambique', numeric='508', official_name='Republic of Mozambique'),
 Country(alpha_2='MR', alpha_3='MRT', flag='🇲🇷', name='Mauritania', numeric='478', official_name='Islamic Republic of Mauritania'),
 Country(alpha_2='MS', alpha_3='MSR', flag='🇲🇸', name='Montserrat', numeric='500'),
 Country(alpha_2='MQ', alpha_3='MTQ', flag='🇲🇶', name='Martinique', numeric='474'),
 Country(alpha_2='MU', alpha_3='MUS', flag='🇲🇺', name='Mauritius', numeric='480', official_name='Republic of Mauritius'),
 Country(alpha_2='MW', alpha_3='MWI', flag='🇲🇼', name='Malawi', numeric='454', official_name='Republic of Malawi'),
 Country(alpha_2='MY', alpha_3='MYS', flag='🇲🇾', name='Malaysia', numeric='458'),
 Country(alpha_2='YT', alpha_3='MYT', flag='🇾🇹', name='Mayotte', numeric='175'),
 Country(alpha_2='NA', alpha_3='NAM', flag='🇳🇦', name='Namibia', numeric='516', official_name='Republic of Namibia'),
 Country(alpha_2='NC', alpha_3='NCL', flag='🇳🇨', name='New Caledonia', numeric='540'),
 Country(alpha_2='NE', alpha_3='NER', flag='🇳🇪', name='Niger', numeric='562', official_name='Republic of the Niger'),
 Country(alpha_2='NF', alpha_3='NFK', flag='🇳🇫', name='Norfolk Island', numeric='574'),
 Country(alpha_2='NG', alpha_3='NGA', flag='🇳🇬', name='Nigeria', numeric='566', official_name='Federal Republic of Nigeria'),
 Country(alpha_2='NI', alpha_3='NIC', flag='🇳🇮', name='Nicaragua', numeric='558', official_name='Republic of Nicaragua'),
 Country(alpha_2='NU', alpha_3='NIU', flag='🇳🇺', name='Niue', numeric='570', official_name='Niue'),
 Country(alpha_2='NL', alpha_3='NLD', flag='🇳🇱', name='Netherlands', numeric='528', official_name='Kingdom of the Netherlands'),
 Country(alpha_2='NO', alpha_3='NOR', flag='🇳🇴', name='Norway', numeric='578', official_name='Kingdom of Norway'),
 Country(alpha_2='NP', alpha_3='NPL', flag='🇳🇵', name='Nepal', numeric='524', official_name='Federal Democratic Republic of Nepal'),
 Country(alpha_2='NR', alpha_3='NRU', flag='🇳🇷', name='Nauru', numeric='520', official_name='Republic of Nauru'),
 Country(alpha_2='NZ', alpha_3='NZL', flag='🇳🇿', name='New Zealand', numeric='554'),
 Country(alpha_2='OM', alpha_3='OMN', flag='🇴🇲', name='Oman', numeric='512', official_name='Sultanate of Oman'),
 Country(alpha_2='PK', alpha_3='PAK', flag='🇵🇰', name='Pakistan', numeric='586', official_name='Islamic Republic of Pakistan'),
 Country(alpha_2='PA', alpha_3='PAN', flag='🇵🇦', name='Panama', numeric='591', official_name='Republic of Panama'),
 Country(alpha_2='PN', alpha_3='PCN', flag='🇵🇳', name='Pitcairn', numeric='612'),
 Country(alpha_2='PE', alpha_3='PER', flag='🇵🇪', name='Peru', numeric='604', official_name='Republic of Peru'),
 Country(alpha_2='PH', alpha_3='PHL', flag='🇵🇭', name='Philippines', numeric='608', official_name='Republic of the Philippines'),
 Country(alpha_2='PW', alpha_3='PLW', flag='🇵🇼', name='Palau', numeric='585', official_name='Republic of Palau'),

In [26]:
error_path = "../results/country_errors.parquet"

if os.path.exists(error_path):
    error_df = pd.read_parquet(error_path)
    error = set(error_df.gid.to_list())
    completed.update(error)
else:
    error_df = pd.DataFrame(columns=["country", "gid", "error"])

In [27]:
error_df

              country  gid                                              error
0           Hong Kong  HKG  The requested "HKG" is not part of GADM. The c...
1      United Kingdom  GBR  Must have equal len keys and value when settin...
2                Fiji  FJI                                      'coordinates'
3  Dominican Republic  DOM  Manifest from NASA DAAC (https://ladsweb.modap...
4            Colombia  COL  Manifest from NASA DAAC (https://ladsweb.modap...
5               China  CHN  Must have equal len keys and value when settin...
6            Botswana  BWA  Manifest from NASA DAAC (https://ladsweb.modap...
7          Antarctica  ATA  Unable to transform edge (296697.215020, 17747...
8            Anguilla  AIA  y dimension not found. 'rio.set_spatial_dims()...

In [ ]:
import shutil
import numpy as np
from conflict_monitoring_ntl.satellites import BlackMarblePy, GHSLSurface
from conflict_monitoring_ntl.transform import RasterPipeline
from conflict_monitoring_ntl.utils import binarize_xarray, get_combined_mask, get_non_nan_flat_array
from rasterio.enums import Resampling
import datetime
from sklearn.metrics import confusion_matrix

rasters = [GHSLSurface(), BlackMarblePy(frequency="monthly")]
transformations = [{"reproject_match": {"resampling": Resampling.sum}}, {}]
date = datetime.date(2020, 1, 1)

with tqdm(pycountry.countries, desc="Calculating confusion matrix:") as pbar:

    for country_dto in pbar:
        
        country = country_dto.name
        gid = country_dto.alpha_3

        pbar.set_postfix(country=country)

        if gid in completed:
            continue

        try:
            
            gdf = pygadm.Items(admin=gid, content_level=1)
        
            pixels = 0
            conf_mat = np.zeros(4, dtype=np.int64)


            for i in tqdm(range(len(gdf)), desc="Processing Provinces"):

                province_gdf = gpd.GeoDataFrame(gdf.iloc[[i]].geometry).set_crs("EPSG:4326")

                pipeline = RasterPipeline(province_gdf, date, rasters, transformations)
                ds = pipeline.run()

                # make sure we compare non-nan areas
                mask = get_combined_mask(ds)
                ds = ds.where(mask)

                ghsl_pop_binary = binarize_xarray(ds.ghsl_surface, 2500)
                y_true = get_non_nan_flat_array(ghsl_pop_binary)

                bm_binary = binarize_xarray(ds.black_marble_radiance_monthly, 1.0)
                y_pred = get_non_nan_flat_array(bm_binary)

                assert y_pred.shape == y_true.shape

                conf_mat += confusion_matrix(y_true, y_pred).flatten()
                pixels += mask.sum().item()

            data = [country, gid, pixels, *conf_mat.tolist()]
            df = pd.concat([pd.DataFrame([data], columns=df.columns), df], ignore_index=True)
            df.to_parquet(checkpoint_path)

            bm_path = Path(os.path.abspath('')).parent / "data" / "black_marble"
            shutil.rmtree(bm_path)  
            bm_path.mkdir(exist_ok=True)
                
        except Exception as e:

            data = [country, gid, str(e)]
            error_df = pd.concat([pd.DataFrame([data], columns=error_df.columns), error_df], ignore_index=True)
            error_df.to_parquet(error_path)